name: Build & Deploy with Ansible Cluster

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull existing image for cache (ignore errors if not exists)
        run: docker pull isshomin/build-cluster:latest || true

      - name: Build Docker image with cache
        run: |
          docker build \
            --cache-from=isshomin/build-cluster:latest \
            -t isshomin/build-cluster:latest .

      - name: Push Docker image
        run: docker push isshomin/build-cluster:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
