name: Build & Deploy with Ansible Cluster

on:
  push:
    branches:
      - main

jobs:
  build-ec2:
    runs-on: [self-hosted, ec2-runner]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image (EC2)
        run: docker build -t isshomin/build-cluster:ec2-${{ github.sha }} .

      - name: Push Docker image (EC2)
        run: docker push isshomin/build-cluster:ec2-${{ github.sha }}

  build-local:
    runs-on: [self-hosted, local-runner]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image (Local)
        run: docker build -t isshomin/build-cluster:local-${{ github.sha }} .

      - name: Push Docker image (Local)
        run: docker push isshomin/build-cluster:local-${{ github.sha }}

  promote-latest:
    runs-on: [self-hosted, controller]
    needs: [build-local, build-ec2]
    if: always()
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Promote EC2 build to latest (if succeeded)
        if: needs.build-ec2.result == 'success'
        run: |
          docker pull isshomin/build-cluster:ec2-${{ github.sha }}
          docker tag isshomin/build-cluster:ec2-${{ github.sha }} isshomin/build-cluster:latest
          docker push isshomin/build-cluster:latest

      - name: Promote Local build to latest (fallback if EC2 failed)
        if: needs.build-ec2.result != 'success' && needs.build-local.result == 'success'
        run: |
          docker pull isshomin/build-cluster:local-${{ github.sha }}
          docker tag isshomin/build-cluster:local-${{ github.sha }} isshomin/build-cluster:latest
          docker push isshomin/build-cluster:latest

  deploy:
    runs-on: [self-hosted, controller]
    needs: promote-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
